### PR TITLE
Get accounts fixes

### PR DESCRIPTION
**Pull request by AssafMiron**
### What does this PR do?
- Added a way to filter only Failed Accounts for Invoke-BulkAccountActions
- Updated README to show this change

### What ticket does this PR close?
Resolves issue raised internally

#### Documentation
- [X] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs

### CODE REVIEW

**Comment by AssafMiron** [comment]
updated formatting

**Comment by engkeen-source** [comment]
Hi @AssafMiron 
Im trying to run the new script, but it prompt for confirmation every 50 account, can you help to get rid of the confirmation dialog

Untitled

**Comment by engkeen-source** [comment]
Hi @AssafMiron 
I had tried and still cannot go pass 1000 account.

Attached console powershell logs upon enable -debug -verbose

[pslogs.txt](https://github.com/cyberark/epv-api-scripts/files/6975900/pslogs.txt)

**Comment by AssafMiron** [comment]
Try looking at the parameter of " MaxDisplayedRecords  " in the PVWA Options
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PASREF/Options%20-%20Search%20Results.htm

If that is 1000, this might be the issue

another thing you can test is running the script with -Limit 2000 (for
example)

Let me know if that works

Regards,
Assaf

**Comment by engkeen-source** [comment]
Hi @AssafMiron 
I think this is REST API limitation which only return 1k account. 

I found a workaround to extract all account.

- get all safe
- loop through each safe and each all account
- add all account in one variable

I use psPAS to build the script. 

You can proceed to close the issue or declare as API limitation.

**Pull request merged**
